name: Man10Shop
version: 1.0
depend:
  - Man10CommonLibs
  - Vault
  - Man10OfflineBank
main: red.man10.man10shop.Man10Shop
auther: [forest611]
api-version: 1.16
commands:
  createshop:
    default: op
  man10shop:
    default: op
  editshop:
    default: op
  shop:
    default: op