name: Man10Shop
version: 1.0
softdepend:
  - Man10CommonLibs
  - Vault
main: red.man10.man10shop.Man10Shop
auther: [forest611]
api-version: 1.13
commands:
  createshop:
    default: op
  man10shop:
    default: op
  shopbal:
    default: op